# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12z6_0ExFitT1IxuZhlNA-Dqaj0RgPTk5
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {
    'Age': [20, 25, 30, 35],
    'Salary': [20000, 50000, 80000, 100000]
}
df = pd.DataFrame(data)

print("Before Normalization:")
print(df)

scaler = MinMaxScaler()
normalized = scaler.fit_transform(df)

df_normalized = pd.DataFrame(normalized, columns=['Age', 'Salary'])

print("\nAfter Normalization:")
print(df_normalized)